
package ar.edu.utn.frre.dacs.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProvinciaServiceService", targetNamespace = "http://www.frre.utn.edu.ar/wsdl", wsdlLocation = "http://localhost:8080/jax-ws-server/ProvinciaServiceService/SimpleProvinciaServiceImpl?wsdl")
public class ProvinciaServiceService
    extends Service
{

    private final static URL PROVINCIASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVINCIASERVICESERVICE_EXCEPTION;
    private final static QName PROVINCIASERVICESERVICE_QNAME = new QName("http://www.frre.utn.edu.ar/wsdl", "ProvinciaServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jax-ws-server/ProvinciaServiceService/SimpleProvinciaServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROVINCIASERVICESERVICE_WSDL_LOCATION = url;
        PROVINCIASERVICESERVICE_EXCEPTION = e;
    }

    public ProvinciaServiceService() {
        super(__getWsdlLocation(), PROVINCIASERVICESERVICE_QNAME);
    }

    public ProvinciaServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVINCIASERVICESERVICE_QNAME, features);
    }

    public ProvinciaServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROVINCIASERVICESERVICE_QNAME);
    }

    public ProvinciaServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVINCIASERVICESERVICE_QNAME, features);
    }

    public ProvinciaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvinciaServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProvinciaService
     */
    @WebEndpoint(name = "ProvinciaServicePort")
    public ProvinciaService getProvinciaServicePort() {
        return super.getPort(new QName("http://www.frre.utn.edu.ar/wsdl", "ProvinciaServicePort"), ProvinciaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvinciaService
     */
    @WebEndpoint(name = "ProvinciaServicePort")
    public ProvinciaService getProvinciaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.frre.utn.edu.ar/wsdl", "ProvinciaServicePort"), ProvinciaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVINCIASERVICESERVICE_EXCEPTION!= null) {
            throw PROVINCIASERVICESERVICE_EXCEPTION;
        }
        return PROVINCIASERVICESERVICE_WSDL_LOCATION;
    }

}
